spring:
  application:
    name: product
  mongodb:
    host: "localhost"
    port: 27017
    database: "test"
    username: "admin"
    password: "admin"
    authentication-database: "admin"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/realms/clownstore/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: "OrderCreatedEvent:com.clownstore.product.kafka.OrderCreatedEvent"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.type.mapping: "StockReservedEvent:com.clownstore.product.kafka.StockReservedEvent"
server:
  port: 8081

