spring:
  application:
    name: cart

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/realms/clownstore/protocol/openid-connect/certs
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: "StockReservedEvent:com.clownstore.cart.kafka.StockReservedEvent"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082

product:
  service:
    url: http://localhost:8080
